Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "log/**/*"
    - "tmp/**/*"
